name: khsomati
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  awesome_dialog: ^3.3.0
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
 
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  http: ^1.6.0
  image_picker: ^1.2.1
  intl_phone_field: ^3.2.0
  lottie: ^3.3.2
  permission_handler: ^12.0.1
<<<<<<< HEAD
  firebase_messaging: ^16.0.4

=======
>>>>>>> e7af9dbbc9840c09443a95d0f319e97159cb6344
  shared_preferences: ^2.5.3
  pinput: ^5.0.2
  url_launcher: ^6.3.2
  flutter_html: ^3.0.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/image_logo_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logos/image_logo_app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logos/image_logo_app.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logos/image_logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/lotties/
    - assets/fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
